---
-   name: Install the Symfony installer
    sudo: yes
    shell: curl -LsS http://symfony.com/installer -o /usr/local/bin/symfony && chmod a+x /usr/local/bin/symfony
    args:
        creates: /usr/local/bin/symfony
