---
-   name: Install php5-fpm package
    sudo: yes
    apt: name=php5-fpm state=latest

#Needed for PHP 5.4
# -   name: Set permissions on socket - owner
#     lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;listen.owner' line='listen.owner = www-data'"
#     notify: Restart php5-fpm

# -   name: Set permissions on socket - group
#     lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;listen.group' line='listen.group = www-data'"
#     notify: Restart php5-fpm

# -   name: Set permissions on socket - mode
#     lineinfile: "dest=/etc/php5/fpm/pool.d/www.conf state=present regexp='^;listen.mode' line='listen.mode = 0660'"
#     notify: Restart php5-fpm

-   name: Ensure date.timezone is set to specified value in fpm php.ini
    lineinfile: dest=/etc/php5/fpm/php.ini
                regexp='date.timezone ='
                line='date.timezone = {{ php5_timezone }}'
    notify: Restart php5-fpm

-   name: Ensure display_errors is set to specified value in fpm php.ini
    lineinfile: dest=/etc/php5/fpm/php.ini
                regexp='display_errors ='
                line='display_errors = {{ php5_display_errors }}'
    notify: Restart php5-fpm

-   name: Ensure error_reporting is set to specified value in fpm php.ini
    lineinfile: dest=/etc/php5/fpm/php.ini
                regexp='error_reporting ='
                line='error_reporting = {{ php5_error_reporting }}'
    notify: Restart php5-fpm

-   name: 'Ensure mbstring.func_overload is set to specified value in fpm php.ini'
    lineinfile: dest=/etc/php5/fpm/php.ini
                regexp='mbstring.func_overload ='
                line='mbstring.func_overload = {{ php5_mbstring_func_overload }}'
    notify: Restart php5-fpm

-   name: Ensure xdebug.max_nesting_level is set to specified value in fpm php.ini
    lineinfile: dest=/etc/php5/fpm/php.ini
                regexp='xdebug.max_nesting_level ='
                line='xdebug.max_nesting_level = {{ php5_xdebug_max_nesting_level }}'
    notify: Restart php5-fpm

-   name: Ensure post_max_size is set to specified value in fpm php.ini
    lineinfile: dest=/etc/php5/fpm/php.ini
                regexp='post_max_size ='
                line='post_max_size = {{ php5_post_max_size }}'
    notify: Restart php5-fpm

-   name: Ensure upload_max_filesize is set to specified value in fpm php.ini
    lineinfile: dest=/etc/php5/fpm/php.ini
                regexp='upload_max_filesize ='
                line='upload_max_filesize = {{ php5_upload_max_filesize }}'
    notify: Restart php5-fpm
