---
-   name: Uninstall Apache2 packages
    sudo: yes
    apt: name=apache2 state=absent purge=yes force=yes

-   name: Install Nginx package
    sudo: yes
    apt: name=nginx state=latest

-   name: Install Nginx packages
    sudo: yes
    apt: name={{ item }} state=latest
    with_items: nginx_packages

-   name: Create Nginx avaliable sites
    sudo: yes
    template: src={{ item.value.source_config_template }}.conf dest=/etc/nginx/sites-available/{{ item.key }}.conf
    with_dict: nginx_sites

-   name: Enable Nginx avaliable sites
    sudo: yes
    shell: ln --symbolic /etc/nginx/sites-available/{{ item.key }}.conf /etc/nginx/sites-enabled/{{ item.key }}.conf
    args:
        creates: /etc/nginx/sites-enabled/{{ item.key }}.conf
    with_dict: nginx_sites
    notify: Restart Nginx

-   name: Add enabled Nginx avaliable sites to /etc/hosts
    sudo: yes
    lineinfile: dest=/etc/hosts
                regexp='{{ item.value.server_name }}'
                line='127.0.0.1 {{ item.value.server_name }}'
    with_dict: nginx_sites
